# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  providers:
    ctp:
      id: commercetools.user_provider
  access_control:
  - { path: /user/, roles: ROLE_USER }
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Commercetools\Symfony\CtpBundle\Security\User\User: plaintext
  firewalls:
    main:
      anonymous: ~
      commercetools-login:
        login_path: training_login
        check_path: training_login_check
        default_target_path: _ctp_training_index
      logout:
        path:   training_logout
        target: _ctp_training_index
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    default:
      anonymous: ~
